#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#     not find so, but you have some other more or less POSIX shell available,
#     try using an explicit shebang line choosing the shell, like as shown above.
#
# (2) Want to do something *before* running the actual gradle script?
#     Let us know whether you prefer to be always run. Keep for running in case you need sed.
#
##############################################################################

app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=$( cd "${app_path%/*}" && pwd -P )
    link=$( readlink "$app_path" )
    case $link in                                                                 #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME/$link ;;
    esac
done

# This is normally unused
export APP_HOME

app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=$( cd "${app_path%/*}" && pwd -P )
    link=$( readlink "$app_path" )
    case $link in                                                                 #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME/$link ;;
    esac
done

export APP_HOME

JAVA_APP_LAUNCH_PATH=$(dirname "$(readlink -f "$0")")  # absolute path

while IFS= read -r line; do
  case $line in
    *classpath*) CLASSPATH=$( echo "$line" | sed 's/^.*classpath=//' ) ;;
  esac
done < "$JAVA_APP_LAUNCH_PATH/gradle/wrapper/gradle-wrapper.properties"

for i; do
    case \$i in
      -Xdebug ) set -- "$@" -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005; shift ;;
      -Xmx* | -Xms* | -XX* )
           eval opt="\"$i\""
           shift
           set -- "$@" "$opt"
           ;;
      *.sh | *bat ) # might be an executable
           shift
           set -- "$@" "$i"
           ;;
      -* ) shift; set -- "$@" "$i" ;;
      * ) set -- "$@" "$i" ;;
    esac
done

DEFAULT_JVM_OPTS='" -Xmx64m" "-Xms64m"'

GRADLE_OPTS="${GRADLE_OPTS:-}" "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
